### PR TITLE
Less backend calls

### PR DESCRIPTION
**Pull request by khanduri**

### CODE REVIEW

**Comment by mahendra** [comment]
+ @BlaineAtAffirm for merging.

lgtm.

**Comment by jimjh** [comment]
Should we write a more generic function for throttling?

**Comment by khanduri** [comment]
I don't think it'll be worth it since the code is contained to this page and the call is specific to the one module that updates the event graph. 

I don't mind writing a generic method, but I don't know if it'll be used on other pages. Note how the functionality is embedded into the page's script tag. I rather not make this a refactor task since all I was hoping to accomplish is get rid of the redundant backend calls we're currently making.

**Comment by khanduri** [comment]
bump for @BlaineAtAffirm . We can close this if we think we won't be using it. I think this was already merged in the main cabot repo a while back

**Comment by mahendra** [comment]
+ @elainearbaugh for review + merge

**Comment by elainearbaugh** [comment]
lgtm

**Comment by elainearbaugh** [comment]
trigger build

**Pull request merged**
