### PR TITLE
User can select services when creating/updating a schedule

### PR DESCRIPTION
**Pull request by elainearbaugh**

### CODE REVIEW

**Comment by elainearbaugh** [comment]
screen shot 2017-02-15 at 4 25 58 pm

**Comment by elainearbaugh** [comment]
trigger build

**Comment by elainearbaugh** [comment]
trigger build with updated jenkins job

**Comment by mahendra** [comment]
I deleted the image since it contained affirm's pagerduty setup information (keys, paths etc.). Please note that Cabot is a public repository :-)

**Comment by elainearbaugh** [comment]
Will be more careful in the future. sorry!

**Pull request merged**
