### PR TITLE
fix requirements

### PR DESCRIPTION
**Pull request by BlaineAtAffirm**

### CODE REVIEW

**Comment by mahendra** [comment]
why was this required?

**Comment by BlaineAtAffirm** [comment]
Because it wouldn't install with the requirements in there already. Not
enough things were pinned i assume, so some dependencies changed

**Comment by mahendra** [comment]
:+1:

**Comment by mahendra** [comment]
@elainearbaugh @BlaineAtAffirm is this still required

**Comment by elainearbaugh** [comment]
Installing requirements is working fine for me, would assume it's not required

**Comment by BlaineAtAffirm** [comment]
lol if it pre-dates Elaine, then I'm sure it's not needed

**Pull request closed without merging**
