### PR TITLE
Infra 3704 change status check model

### PR DESCRIPTION
**Pull request by elainearbaugh**
Goal: Move fields for specific StatusCheck subclasses out of the StatusCheck model. Decided to do it this way instead of making a new check model because I'd have to move jenkins/http checks over to the new model and make changes everywhere checks were mentioned, so it'd be a lot more work than this, and the status check model was pretty close to what I wanted anyways. 

There's a schema migration (0022) to add these fields to subclasses and rename the fields in statuscheck to prevent duplicates, data migration (0023) to move data from StatusCheck to the subclass tables, schema migration (0024) to remove the fields in statuscheck. 

Testing so far: create checks of each type locally, then run migrations 22-24 and make sure the checks were the same. Create new checks after running all migrations to ensure nothing was missing in the models.

### CODE REVIEW

**Comment by elainearbaugh** [comment]
Tried deploying to stage and validating checks, that also worked

**Comment by mahendra** [comment]
Thank you for the cleanup. This is really good.

**Comment by mahendra** [comment]
please ensure that we are not deleting tables / columns in the forward path.

**Comment by elainearbaugh** [comment]
@mahendra oh I was deleting columns in the third migration--1st renames columns in statuscheck and creates them in influxstatuscheck etc, 2nd moves the data from statuscheck to influxstatuscheck, and third removes the columns in statuscheck. Is this ok?

double checked that the deleted columns are only the ones that were renamed and moved

**Pull request merged**
